sudo: required
language: go
go_import_path: github.com/69th-byte/SmartDex-Chain

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on


jobs:
  include:

  - stage: Lint
    sudo: false
    go: '1.12.x'
    git:
      submodules: false
      script:
        - go run build/ci.go lint

  - stage: Build and test
    go: '1.12.x'
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - while sleep 540; do echo "[ still running ]"; done &
    - go run build/ci.go test -coverage
    - kill %1
    after_success:
    - bash <(curl -s https://codecov.io/bash)

  - go: '1.11.x'
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - while sleep 540; do echo "[ still running ]"; done &
    - go run build/ci.go test -coverage
    - kill %1

  - stage: Github release
    go: '1.12.x'
    script:
      - GOARCH=amd64 GOOS=linux go build -o ./build/bin/sdx-linux-amd64 -v ./cmd/sdx
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      overwrite: true
      file_glob: true
      file: build/bin/sdx-*
      skip_cleanup: true
      on:
        tags: true

  - stage: Build and push image
    services:
      - docker
    install: skip
    before_script:
      - docker build -t 69th-byte/SmartDex-Chain .
      - docker build -t swapdex/node-testnet -f Dockerfile.node .
    script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag 69th-byte/SmartDex-Chain 69th-byte/SmartDex-Chain:latest
      - docker push 69th-byte/SmartDex-Chain:latest
      - docker tag 69th-byte/SmartDex-Chain 69th-byte/SmartDex-Chain:$TRAVIS_BUILD_ID
      - docker push 69th-byte/SmartDex-Chain:$TRAVIS_BUILD_ID
      - docker tag swapdex/node-testnet swapdex/node-testnet:latest
      - docker push swapdex/node-testnet:latest
      - docker tag swapdex/node-testnet swapdex/node-testnet:$TRAVIS_BUILD_ID
      - docker push swapdex/node-testnet:$TRAVIS_BUILD_ID

  - stage: Build and push image (tagged)
    services:
      - docker
    install: skip
    before_script:
      - docker build -t 69th-byte/SmartDex-Chain .
      - docker build -t 69th-byte/SmartDex-Chain -f Dockerfile.node .
    script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag 69th-byte/SmartDex-Chain 69th-byte/SmartDex-Chain:latest
      - docker push 69th-byte/SmartDex-Chain:latest
      - docker tag 69th-byte/SmartDex-Chain 69th-byte/SmartDex-Chain:$TRAVIS_TAG
      - docker push 69th-byte/SmartDex-Chain:$TRAVIS_TAG
      - docker tag 69th-byte/SmartDex-Chain swapdex/node-testnet:latest
      - docker push swapdex/node-testnet:latest
      - docker tag swapdex/node-testnet swapdex/node-testnet:$TRAVIS_TAG
      - docker push swapdex/node-testnet:$TRAVIS_TAG

stages:
  - name: Lint
  - name: Build and test
  - name: Github release
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = 69th-byte/SmartDex-Chain
  - name: Build and push image
    if: type != pull_request AND branch = master AND tag IS blank AND repo = 69th-byte/SmartDex-Chain
  - name: Build and push image (tagged)
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = 69th-byte/SmartDex-Chain
