FROM golang:1.11-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers

ADD . /SmartDex-Chain
RUN cd /SmartDex-Chain && make bootnode

RUN chmod +x /SmartDex-Chain/build/bin/bootnode

FROM alpine:latest

LABEL maintainer="dev@smartdex.net"

WORKDIR /sdx

COPY --from=builder /SmartDex-Chain/build/bin/bootnode /usr/local/bin/bootnode

COPY docker/bootnode ./

EXPOSE 30301

ENTRYPOINT ["./entrypoint.sh"]

CMD ["-verbosity", "6", "-nodekey", "bootnode.key", "--addr", ":30301"]
