FROM golang:1.10-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers

ADD . /SDXchain
RUN cd /SDXchain && make bootnode

RUN chmod +x /SDXchain/build/bin/bootnode

FROM alpine:latest

LABEL maintainer="deva@swapdex.net"

WORKDIR /SDXchain

COPY --from=builder /SDXchain/build/bin/bootnode /usr/local/bin/bootnode

COPY docker/bootnode ./

EXPOSE 30301

ENTRYPOINT ["./entrypoint.sh"]

CMD ["-verbosity", "6", "-nodekey", "bootnode.key", "--addr", ":30301"]
